### ISSUE TITLE
Different estimated T in figure 1?

### ISSUE THREAD

**Issue by YongtaoGE** [giorgiop/loss-correction#3]
Hi, @giorgiop. In your code,  the process of estimating backward T and forward T is just the same, so how could you get different accurracy of backward T and forward T with different noise rate in your paper? 
![estimate t](https://user-images.githubusercontent.com/22744013/41826200-49e6b83c-785a-11e8-9a13-dbc11ab02858.PNG)

**Comment by giorgiop** [comment]
It is true that the estimated matrix T is the same. But it is then used by the two different algorithms for loss correction, so the results are different.

**Comment by YongtaoGE** [comment]
I have misunderstood the figure. 
**T is known (solid line), T is estimated (dotted line).**
@giorgiop ,Is that right?

**Comment by giorgiop** [comment]
Correct!

**Comment by YongtaoGE** [comment]
Thank you!
